# Config file for generate_data_v1, which generates 650 SFSs of the two_pop_split
# model
dem_params:
  mutation_rate: !!float 2.9e-9
  recombination_rate: !!float 1.25e-17
  ancestral_population_size: !!float 2e5
  split_population_size: !!float 1e5
  t_split: !!float 1e3
  mig_rate: !!float 1e-5
  seq_len: !!float 1e6
  ploidy: !!int 2
pipeline_params:
  poolseq_depths: [10, 30, 50, 70, 90]
  sample_sizes: [10, 50, 100, 200, 500]
  data_dir: /scratch/djb3ve/Demographic-inference-with-pool-seq-data/data/
  num_of_demography_sim_replicates: !!int 5
  num_of_poolseq_noising_replicates: !!int 5
  rounding_method: counts
  ignore_multiallelic_site: !!bool False
