# Config file for QA test "test_sfs_generation.py"
dem_params:
  mutation_rate: !!float 2.9e-9
  recombination_rate: !!float 1.25e-17
  ancestral_population_size: !!float 2e5
  split_population_size: !!float 1e5
  t_split: !!float 1e3
  mig_rate: !!float 1e-5
  seq_len: !!float 1e5
  ploidy: !!int 2
pipeline_params:
  poolseq_depths: [10, 30, 50, 70, 90]
  sample_sizes: [10, 50, 100, 200, 500]
  data_dir: /scratch/djb3ve/Demographic-inference-with-pool-seq-data/data/
  output_file: /scratch/djb3ve/Demographic-inference-with-pool-seq-data/qa_testing/probs2.txt
  num_of_demography_sim_replicates: !!int 5
  num_of_poolseq_noising_replicates: !!int 5
  rounding_method: probs
  ignore_multiallelic_site: !!bool False
abc_params:
  steps: !!int 6
  n_samples: !!int 10
  epsilon_percentile: !!float 0.1
  epsilon_init: [!!float 1e10]
  prior_bounds:
    log_n_1: [[3], [7]]
    log_n_2: [[3], [7]]
    log_t_split: [[1], [5]]
    log_m: [[-7], [-3]]
