# Config file for generate_data_v4
dem_params:
  mutation_rate: !!float 2.9e-9
  recombination_rate: !!float 1.25e-17
  ancestral_population_size: !!float 2e5
  split_population_size: !!float 1e5
  t_split: !!float 1e6
  mig_rate: !!float 0
  seq_len: !!float 1e6
  ploidy: !!int 2
pipeline_params:
  sample_sizes: [10, 50, 100, 200]
  poolseq_depths: [10, 30, 50, 70, 90]
  data_dir: /scratch/djb3ve/Demographic-inference-with-pool-seq-data/data_v4/
  output_dir: /scratch/djb3ve/Demographic-inference-with-pool-seq-data/data_v4/
  num_of_demography_sim_replicates: !!int 3
  num_of_poolseq_noising_replicates: !!int 3
  rounding_method: counts
